//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetWithOutIdentity.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_USUARIOS
    {
        public int ID_CAT_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string APPELIDO_PATERNO { get; set; }
        public string APELLIDO_MATERNO { get; set; }
        public string USUARIO { get; set; }
        public string ROL { get; set; }
        public string CORREO { get; set; }
    }
}
